UiPath/ProcessMining-pm-utils

macros/generic_tests/test_type_boolean.sql, macros/generic_tests/test_type_date.sql, macros/generic_tests/test_type_double.sql, macros/generic_tests/test_type_integer.sql, macros/generic_tests/test_type_timestamp.sql
By default fieldnames are encapsulated in (extra) double quotes, these have to be removed
=> fix: have test_type macros use the correct fieldname (DNA-3115 - DNA-3159)

README.md, macros/multiple_databases/string_agg.sql
- String_agg function aggregates strings of type nvarchar(2000), which introduces the limitation that also the aggregate string has a maximum length 2000. This limitation should be acceptable.
- The variant macro still makes use internally of nvarchar(max), because when determining the variant IDs, the length may be more than 2000.
=> feat: string_agg only works with a maximum length of 2000 (DNA-6774: DNA-6981)

README.md, macros/multiple_databases/create_index.sql
- Can be applied on source tables if parameter is defined
- When no parameter is defined, use on other models
=> fix: use relation for create index (DNA-7566: DNA-7583)

README.md, macros/generic_tests/test_exists.sql, macros/generic_tests/test_field_length.sql, macros/generic_tests/test_format.sql, macros/generic_tests/test_not_null.sql, macros/generic_tests/test_one_column_not_null.sql, macros/generic_tests/test_unique.sql, macros/generic_tests/test_unique_combination_of_columns.sql
- Implement not_null and unique test.
- Include in tests that run on source data that the field should exist when running the test.
- Include optional dummy parameter 'name' to create compatibility with dbt v1.0.
=> feat: support for user-friendly errors (DNA-9136: DNA-9580, DNA-9789)

dbt_project.yml, macros/generic_tests/test_type_timestamp.sql, macros/multiple_databases/timestamp_from_date.sql, macros/multiple_databases/timestamp_from_parts.sql, macros/multiple_databases/to_timestamp.sql
Change `datetime` to `datetime2` datatypes with 3 digit precision in SQL Server.
Context: https://www.sqlines.com/sql-server/datetime_or_datetime2_3
=> refactor: use datetime2 instead of datetime in SQL Server DNA-11164 (DNA-12524)

macros/multiple_databases/date_from_timestamp.sql, macros/multiple_databases/timestamp_from_date.sql, macros/multiple_databases/timestamp_from_parts.sql, macros/multiple_databases/to_boolean.sql, macros/multiple_databases/to_date.sql, macros/multiple_databases/to_double.sql, macros/multiple_databases/to_integer.sql, macros/multiple_databases/to_time.sql, macros/multiple_databases/to_timestamp.sql
In the updates of the typecasting macros null was written in capital letters, set this to lower case for linting and consistency purposes.
=> DNA-14397  (DNA-14894) fix: put null in lowercase

dbt_project.yml, macros/multiple_databases/date_from_timestamp.sql, macros/multiple_databases/to_boolean.sql, macros/multiple_databases/to_date.sql, macros/multiple_databases/to_double.sql, macros/multiple_databases/to_integer.sql, macros/multiple_databases/to_time.sql, macros/multiple_databases/to_timestamp.sql
- The try_to_date function in the date_from_timestamp requires a string as input before casting to date can be done.
- This will be released as a bug fix together with https://github.com/UiPath/ProcessMining-pm-utils/pull/50. So update to version 0.14.1.
=> fix: date_from_timestamp requires varchar as input for try_to function (DNA-14397: DNA-15339)

macros/generic/optional.sql
In the `optional` macro we assumed the `relation` always exists. This did not work for optional tables. Added functionality to deal with this.
Tested:
- Source table does not exist.
- Source table does exist, but field does not exist.
- Source table does exist and field does exist.
- Source table is mandatory, but field is optional (and exists)
=> fix: optional field on optional tables DNA-15851

dbt_project.yml, macros/multiple_databases/string_agg.sql
- Make string_agg consistent to output null instead of the empty string in Snowflake when string_agg is applied on only null values.
- Why:
Merge to main, but release will be done later.
=> fix: make string_agg consistent when aggregating null values (DNA-16185: DNA-17242)

README.md, dbt_project.yml, macros/generic/optional.sql
- Update the optional() implementation to prevent data type casting on a field that can be selected when relation is not a source. 
- This is to prevent potential 2nd data type casting on already casted fields. 2nd data type casting is a problem for date, time, and datetime fields when a format variable is provided different from the database standard (Snowflake only).
- Why:
=> fix: optional without casting (DNA-18184: DNA-18273)

macros/generic/optional.sql, macros/generic/optional_table.sql, macros/multiple_databases/as_varchar.sql, macros/multiple_databases/to_boolean.sql, macros/multiple_databases/to_date.sql, macros/multiple_databases/to_double.sql, macros/multiple_databases/to_integer.sql, macros/multiple_databases/to_timestamp.sql, macros/multiple_databases/to_varchar.sql
- Mandatory and optional macro's are enabled for Databricks
- Casting macro's that are implemented for Databricks: `to_boolean`, `to_date`, `to_double`, `to_int`, `to_timestamp`, `to_varchar`, `as_varchar`
- Documentation to be done in separate PR.
- Why: Merge to dev branch designated for Databricks. We will merge to main once this is completely implemented.
=> Enable databricks casting, mandatory and optional macros DNA-17332 [DNA-17608 + DNA-17635]

macros/multiple_databases/date_from_timestamp.sql, macros/multiple_databases/datediff.sql, macros/multiple_databases/timestamp_from_date.sql, macros/multiple_databases/timestamp_from_parts.sql
- Implemented Databricks variant for the following macro's: `datediff`, `date_from_timestamp`, `timestamp_from_date`, `timestamp_from_parts`
- `datediff` implements all units of time as for SQL Server or Snowflake, but there are differences when it comes to rounding. F.e. for weeks, the difference between `2017-11-21` and `2017-11-01` in Snowflake is 3, whereas in Databricks, it is 2, regardless whether the implementation is done using date differences or unix seconds.
- Why: Merge to databricks branch
=> Implemented time related macro's for databricks DNA-17332 [DNA-18809]

README.md, macros/multiple_databases/datediff.sql
- The output for datediff using week as datepart is not the same for SQL Server and Snowflake. The difference is caused because Snowflake and SQL Server use a different day as start of the week, for Snowflake this is Monday, for SQL Server this is Sunday. This fix aligns both (week starting on Monday).
- Why:
- We will release this together with the next update for pm_utils
=> fix: datadiff week inconsistency between SQL Server and Snowflake (DNA-17332 / DNA-19251)

macros/generic/mandatory.sql, macros/generic/optional.sql
- Remove unused time option for mandatory/optional macro's since the to_time macro is no longer available.
- [x ] Merge to `dev` (or other) branch
=> Remove unused time option for mandatory/optional macro's DNA-17332 [DNA-19289]

README.md, macros/multiple_databases/timestamp_from_parts.sql
- Refactor `timestamp_from_parts` to accept strings for the time field. This reintroduces the usage of the `time_format` variable in `dbt_project.yml`
=> Refactor timestamp_from_parts to accept time as string DNA-17332 [DNA-17615]

.gitignore, .pipelines/azure-pipelines-integration-tests.yml, .pipelines/profiles.yml, integration_tests/dbt_project.yml, integration_tests/macros/tests.sql, integration_tests/models/schema.yml, integration_tests/models/test_concat.sql, integration_tests/packages.yml
Added a dbt project "Integration tests" that consists of the following:
- A standard `dbt_project.yml` file without any specific settings.
- The `packages.yml` that points to the local version of pm-utils.
- A models folder where we can add `.sql` files with tests. Currently only one file exists for testing the `concat()` function. It creates a table with "actual values" using the function and "expected values"
- A `schema.yml` file where we test the result of the models. In this example, are the actual and expected values the same.
- To support testing whether values are the same, a test macro is implemented in the macros.
Note: when we merge this, we should add the additional files to the .zipignore in the AppTemplates repo: https://github.com/UiPath/ProcessMining-App-Templates/blob/main …
=> test: implement framework for integration tests (DNA-19347: DNA-19404)

macros/multiple_databases/to_double.sql
The `to_double` function was casting to `float` for databricks, which we changed to `double`, since:
- Databricks defaults to type `double` when applying f.e. multiplications on a `float` value
- Precision of `float` is different compared to what SQL Server does
- Why: part of the databricks development
~~- [ ] The version number in `dbt_project.yml`~~ Still on dev branch
=> fix: cast to_double for Databricks to double DNA-15944 (DNA-20110)

macros/multiple_databases/timestamp_from_parts.sql
- Implement manual fallback for milliseconds usage in time formats due to the legacy time parser setting for Databricks.
- Why: Merge to Databricks branch
=> Handle milliseconds in timestamp_from_parts for Databricks DNA-15944 [DNA-20489]

README.md, macros/multiple_databases/charindex.sql
- Implement charindex macro for Spark compatbility.
=> Implement charindex macro DNA-15944 [DNA-20680]

README.md, macros/multiple_databases/dateadd.sql
- Implement charindex macro for Spark compatbility.
- Why:
=> Implement dateadd macro DNA-15944 [DNA-20679]

dbt_project.yml, macros/multiple_databases/dateadd.sql
Explicitly cast `number` to INT in the `dateadd` macro for the Databricks part. Without this cast, we cannot use the `dateadd` function with _day_, _week_, _month_, _quarter_ or _year_ in combination with the `to_integer` pm_utils macro. That last macro returns a `BIGINT` which is not accepted by the functions used in the implementation for the specified periods.
- Why:
=> fix: cast number param for dateadd to int for databricks DNA-15944 (DNA-20849)

dbt_project.yml, macros/multiple_databases/charindex.sql
- For the `charindex` macro, also account for spaces in SQL Server when checking if a field is `null` or not.
- Why:
=> Include spaces in charindex macro for SQL Server DNA-15944 [DNA-20911]

integration_tests/models/schema.yml, integration_tests/models/test_charindex.sql, integration_tests/models/test_dateadd.sql, integration_tests/models/test_to_timestamp.sql
- Adds integration tests for `charindex`, `dateadd` and `to_timestamp` macro's
- Why:
~~- [ ] The version number in `dbt_project.yml`~~
=> Add integration tests for charindex, dateadd, to_timestamp (DNA-19468 / DNA-20817)

README.md, dbt_project.yml, integration_tests/models/schema.yml, integration_tests/models/test_stddev.sql, macros/multiple_databases/stddev.sql
- Add stddev macro to compute the standard deviation
~~- [ ] Merge to `dev` (or other) branch~~
- Why:
=> feat: add stddev macro (DNA-18084 / DNA-21718)

.pipelines/azure-pipelines-integration-tests.yml, README.md, dbt_project.yml, integration_tests/models/schema.yml, integration_tests/models/test_dateadd.sql, macros/multiple_databases/dateadd.sql
- To fix the bug: the `number` argument is casted to a `bigint` for Databricks. Only for Databricks we do computations on this argument which can result in (negative) overflow values when the `number` is of type `int` instead of `bigint`. 
- Simplified the implementation:
- Replaced the `date_add` used for `day` and `week` with the same approach as for the more granular units. We now have 2 different approaches instead of 3 to cover all scenarios.
- Moved the "Jinja set variables" to places more close to where it is used.
- Docs: updated the readme to fix the table of contents and removed the condition that the number of units should be an integer.
- Added tests:
- Additions of more than 25 days. Both in seconds, which we use ourselves, but also in days as this seems to be a more standard …
=> fix: dateadd supports more than 25 days for every unit of time (DNA-21769: DNA-21829)

.pipelines/profiles.yml, README.md, dbt_project.yml, integration_tests/models/schema.yml, integration_tests/models/test_datediff.sql, integration_tests/models/test_diff_weekdays.sql, macros/multiple_databases/datediff.sql, macros/multiple_databases/diff_weekdays.sql
- Update the existing datediff function to make consistent over databases,
- Weeks are defined from Sunday to Saturday
- Added the `week`, `quarter`, and `month` options to Databricks.
- New function diff_weekdays is implemented to return number of days excluding weekends.
- Why:
=> feat: implement datediff for for week days (DNA-24249: DNA-24526 + DNA-24512)

.pipelines/azure-pipelines-integration-tests.yml, README.md, dbt_project.yml, integration_tests/dbt_project.yml, macros/SQL_generators/star.sql
- Make dbt configuration similar to app templates: enable quoting and materialize as table.
- Fix quotes on the star macro for the relation identifier.
- Why:
=> test: set configuration similar to app templates dbt projects (DNA-23644: DNA-25720)

README.md, dbt_project.yml, macros/SQL_generators/optional.sql
Generate an id value when all values in the source field are null.
- When the field doesn't exist, create it with a unique id.
- When the field has at least one value, apply type casting to integer.
- Why:
=> feat: extend optional id by also generating id when all null (DNA-37255)

.pipelines/azure-pipelines-integration-tests.yml, dbt_project.yml, integration_tests/models/schema.yml, macros/SQL_generators/mandatory.sql, macros/SQL_generators/optional.sql
ID data type fields don't need to be integers. Also text IDs are allowed.
Apply to both the optional and mandatory macro.
Impact: numeric fields remain numeric and text fields remain text. This prevents casting to numeric when the values are not numeric and therefore result in errors/null values.
- Why:
=> fix: dont apply type casting to selected id field (DNA-38818)
