dbt_project.yml, third-party_licenses.txt
- update version number
- update third party licenses
=> DNA-5885 (DNA-6480): chore: update pm-utils for release 0.4.0

README.md, macros/generic_tests/test_format.sql
Also moved the test field length in the readme which was not at the correct place
=> feat: implemented test_format (DNA-2746: DNA-6683)

dbt_project.yml
=> DNA-6774 (DNA-7178): chore: update pm-utils for release 0.6.0

macros/multiple_databases/date_from_timestamp.sql
Changed to_date() function to try_to_date() function in date_from_timestamp.sql
=> Use try_to_date() instead of to_date() (DNA-9164 / DNA-10098)

macros/generic_tests/test_exists.sql, macros/generic_tests/test_field_length.sql, macros/generic_tests/test_format.sql, macros/generic_tests/test_not_null.sql, macros/generic_tests/test_one_column_not_null.sql, macros/generic_tests/test_type_boolean.sql, macros/generic_tests/test_type_date.sql, macros/generic_tests/test_type_double.sql, macros/generic_tests/test_type_integer.sql, macros/generic_tests/test_type_timestamp.sql, macros/generic_tests/test_type_varchar.sql, macros/generic_tests/test_unique.sql, macros/generic_tests/test_unique_combination_of_columns.sql
This will fix any errors when SQL Server database collation is set to case sensitive
=> fix: use proper casing for information schema (DNA-10178 / DNA-10713)

license.txt
=> Update license files (DNA-10966 / DNA-11570)

.github/workflows/check_jira_issue_key.yml
ci: add check for jira issue key
=> ci: add check for jira issue key DNA-11484 (DNA-11742)

README.md, dbt_project.yml, macros/generic_tests/test_not_null.sql, macros/multiple_databases/to_varchar.sql
- `to_varchar` casts the empty string to `null`.
- `not_null` test also checks for the empty string.
=> feat/cast blanks to null DNA-12262 (DNA-12840)

dbt_project.yml, macros/generic_tests/test_exists.sql, macros/generic_tests/test_field_length.sql, macros/generic_tests/test_format.sql, macros/generic_tests/test_not_null.sql, macros/generic_tests/test_one_column_not_null.sql, macros/generic_tests/test_unique.sql, macros/generic_tests/test_unique_combination_of_columns.sql
- Implement new log message structure by providing a json object.
- Only implemented on tests that run on sources.
- Severity config is taken into account for tests.
- No readme updates necessary.
=> feat: implement new message structure (DNA-11932: DNA-13647, DNA-13648, DNA-14372)

README.md, macros/generic/mandatory.sql, macros/generic/optional.sql, macros/multiple_databases/to_boolean.sql, macros/multiple_databases/to_date.sql, macros/multiple_databases/to_double.sql, macros/multiple_databases/to_integer.sql, macros/multiple_databases/to_time.sql, macros/multiple_databases/to_timestamp.sql
Description:
- Implement logging in type casting macros.
- Implement the mandatory macro.
Only merge when the warning structure has been validated.
=> feat: conversion warnings (DNA-10851: DNA-13579)

macros/multiple_databases/date_from_timestamp.sql
- Fixes date conversion error for Snowflake.
=> fix: date conversion error (DNA-9778 / DNA-15205)

.github/pull_request_template.md, dbt_project.yml
- update version number (forgotten in previous PR)
- add PR checklist specific to pm-utils.
- Why:
=> chore update version number DNA-15851

macros/multiple_databases/string_agg.sql
- Added string_agg option for Databricks
=> Added string_agg option for Databricks DNA-17332 [DNA-17609]

macros/generic_tests/test_equal_rowcount.sql, macros/generic_tests/test_not_null.sql, macros/generic_tests/test_one_column_not_null.sql, macros/generic_tests/test_unique.sql, macros/generic_tests/test_unique_combination_of_columns.sql, macros/multiple_databases/to_timestamp.sql
Implemented `unique`, `unique_combination_of_columns`, `not_null` test variants for Databricks
=> Implement tests for Databricks DNA-17332 [DNA-17611]

README.md
- Update documentation reflecting Databricks support.
=> Update README with Databricks variant DNA-17332 [DNA-17335]

macros/generic_tests/test_exists.sql
Replace the information schema query with adapter functions/other SQL statements. This makes the change to Databricks easier. In a separate PR these changes will be ported to the dev_databricks branch.
- Why:
=> refactor: information schema queries (DNA-17836: DNA-19270)

macros/generic_tests/test_exists.sql
Port the changes from PR #70 
- Why: databricks dev work is collected on a separate branch
=> feat: port test exist refactor (DNA-17836: DNA-19303)

.pipelines/azure-pipelines-integration-tests.yml, .pipelines/profiles.yml, integration_tests/models/schema.yml, integration_tests/models/test_concat.sql
- Updated integration tests to support Databricks (changing quotes to backticks)
- Updated pipeline to also run on Databricks
- Why:
=> Add databricks support for integration tests (DNA-19468 / DNA-20814)

README.md
Add diff_weekdays to the table of contents.
- Why:
=> docs: add diff_weekdays to toc (DNA-24249)

.pipelines/azure-pipelines-integration-tests.yml
Update dbt-snowflake version for testing. No impact on code.
- Why:
=> ci: update dbt-snowflake version to 1.7.5 (DNA-27331: DNA-28002)

README.md, dbt_project.yml, integration_tests/models/schema.yml, integration_tests/models/test_json.sql, macros/string_functions/json.sql
=> feat: add json macro (DNA-28629: DNA-30268)

.pipelines/azure-pipelines-integration-tests.yml
- update the version of the AzureKeyVault task, since version @1 is deprecated.
- See the integration check on this PR such that it still works :) 
- Why:
~~- [ ] Does it Work on Automation Suite / SQL Server~~
~~- [ ] Does it Work on Automation Cloud / Snowflake~~
~~- [ ] The version number in `dbt_project.yml`~~
=> ci: update AzureKeyVault version DNA-30522

license.txt
Update copyright license year to 2025.
- Why:
=> chore: update license to 2025 (DNA-34544)
